DATASET:
  # Path to training images list file (darknet style) or directory (yolo style)
  TRAIN: "/data/datasets/coco2017/images/train2017"
  # Path to evaluation images list file (darknet style) or directory (yolo style)
  VAL: "/data/datasets/coco2017/images/val2017"
  # Path to class names list file or list of class names
  NAMES: [person, bicycle, car, motorbike, aeroplane, bus, train, truck, boat, traffic light, fire hydrant, stop sign, parking meter, bench, bird, cat,
    dog, horse, sheep, cow, elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee, skis, snowboard,
    sports ball, kite, baseball bat, baseball glove, skateboard, surfboard, tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple,
    sandwich, orange, broccoli, carrot, hot dog, pizza, donut, cake, chair, sofa, pottedplant, bed, diningtable, toilet, tvmonitor, laptop,
    mouse, remote, keyboard, cell phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear, hair drier, toothbrush]
MODEL:
  # Number of classes
  NUM_CLASSES: 80
  # Number of blocks in each stage of the backbone
  BACKBONE_BLOCKS: [4, 8, 4]
  # Number of channels in each stage of the backbone
  BACKBONE_CHANNELS: [48, 96, 192, 384]
  # Name of the pretrained backbone weights file in the weights directory
  BACKBONE_NAME: "qamobileone-2x.pth"
  # Input width and height
  INPUT_SIZE: [352, 352]
TRAIN:
  # Initial learning rate
  LEARNING_RATE: 0.002
  # Gamma for learning rate decay
  GAMMA: 0.05
  # Number of warm-up epochs
  WARMUP_EPOCH: 5
  # Weight decay factor for non-BN parameters
  WEIGHT_DECAY: 3e-4
  # Momentum factor for SGD optimizer
  MOMENTUM: 0.949
  # EMA decay factor
  EMA_DECAY: 0.9998
  # Batch size
  BATCH_SIZE: 96
  # Total training epochs
  END_EPOCH: 300
  # Epochs for learning rate decay
  MILESTONES: [120, 270]
AUGMENT:
  # HSV jitter gains
  HSV_GAIN: [0.015, 0.4, 0.3]
  # Horizontal flip probability
  FLIP_P: 0.5
  # Random crop minimum ratio
  CROP_MIN: 0.5
  # Random narrow maximum ratio
  NARROW_MAX: 1.5
